
elasticsearch:
    image: elasticsearch:2.2.0
    container_name: elasticsearch 
    privileged: true 
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
       - ./elasticsearch/data:/usr/share/elasticsearch/data
logstash:
    image: logstash:2.2.0-1
    container_name: logstash 
    privileged: true 
    restart: always
    ports:
      - 5044:5044
      - 4560:4560
      - 8080:8080
    volumes:
      - ./logstash/conf:/config-dir
      - ./logstash/patterns:/opt/logstash/patterns
    external_links:
      - elasticsearch:elasticsearch
    command: logstash -f /config-dir
filebeat:
    image: olinicola/filebeat:1.0.1 
    container_name: filebeat 
    privileged: true 
    restart: always
    extra_hosts:
      - logstash:172.17.0.1
    volumes:
      - ./filebeat/conf/filebeat.yml:/etc/filebeat/filebeat.yml
      - /data/app/logs/nginx/:/data/logs
      - /var/log:/var/host/log
      - ./filebeat/registry:/etc/registry
kibana:
    image: kibana:4.4.0
    container_name: kibana 
    privileged: true 
    restart: always
    ports:
      - 5601:5601
    external_links:
      - elasticsearch:elasticsearch
